### ISSUE TITLE
Is it working for Other Coins also?

### ISSUE THREAD

**Issue by Marow** [jeffdoubleyou/ubiq-explorer#1]
Hi, 

this explorer looks awesome!
Is it working on DBIX (ethereum thing)?

**Comment by jeffdoubleyou** [comment]
It should work on any Ethereum based coin, but look at #2 .  It's just not ready for out of the box deployment.  You'll need to do some work to get it going at the moment.

**Comment by jeffdoubleyou** [comment]
This should now work for any coin and install out of the box.
