### ISSUE TITLE
npm install not working?

### ISSUE THREAD

**Issue by Marow** [jeffdoubleyou/ubiq-explorer#2]
Is saying they dont have any informations about UbiqExplorer

**Comment by jeffdoubleyou** [comment]
This is not in npm, the automated readme generation created the README and that is just what it did.

I would not consider this project 100% ready to be deployed without some significant work.

You need to install this package by git, along with ubiq-statsdaemon, ubiq-blockdaemon and there are some other pieces that are not even published yet.  It also would require some Nginx configuration and probably some other things that are simply not yet documented.

The pool section would require that you setup an open-ethereum-pool deployment and configure everything in nginx for it.

When I have time, I'll be cleaning all of this up and making it easier to deploy, but I don't have any sort of timeline for this.
